import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { NotebookCrdt, type NotebookCrdtProjection } from './crdt';

interface BinaryFixture {
  encoding: 'base64';
  byteLength: number;
  data: string;
}

interface YrsProducerFixture {
  fixtureFormat: string;
  fixtureVersion: number;
  notebookId: string;
  producer: {
    runtime: string;
    library: string;
    libraryVersion: string;
    clientId: number;
    command: string;
  };
  fullState: {
    update: BinaryFixture;
    stateVector: BinaryFixture;
    expectedProjection: NotebookCrdtProjection;
  };
  incremental: {
    update: BinaryFixture;
    afterStateVector: BinaryFixture;
    expectedProjection: NotebookCrdtProjection;
  };
}

const fixture = JSON.parse(readFileSync(
  new URL('../../../test-fixtures/yjs-v1/yrs-producer.json', import.meta.url),
  'utf8',
)) as YrsProducerFixture;

const decode = (binary: BinaryFixture) => {
  expect(binary.encoding).toBe('base64');
  const bytes = Uint8Array.from(Buffer.from(binary.data, 'base64'));
  expect(bytes.byteLength).toBe(binary.byteLength);
  expect(Buffer.from(bytes).toString('base64')).toBe(binary.data);
  return bytes;
};

describe('Yrs-produced Yjs v1 fixture', () => {
  it('is explicitly generated by the pinned native implementation', () => {
    expect(fixture.fixtureFormat).toBe('storm.dance/yrs-v1-producer');
    expect(fixture.fixtureVersion).toBe(1);
    expect(fixture.producer).toMatchObject({
      runtime: 'rust',
      library: 'yrs',
      libraryVersion: '0.27.3',
    });
    expect(fixture.producer.clientId).toBeGreaterThan(0);
    expect(fixture.producer.command).toContain('generate_yjs_fixture');
  });

  it('loads native full and incremental updates directly in browser Yjs', () => {
    const replica = new NotebookCrdt(fixture.notebookId);
    replica.applyUpdate(decode(fixture.fullState.update));
    expect(replica.snapshot()).toEqual(fixture.fullState.expectedProjection);
    expect(Array.from(replica.encodeStateVector()))
      .toEqual(Array.from(decode(fixture.fullState.stateVector)));

    replica.applyUpdate(decode(fixture.incremental.update));
    expect(replica.snapshot()).toEqual(fixture.incremental.expectedProjection);
    expect(Array.from(replica.encodeStateVector()))
      .toEqual(Array.from(decode(fixture.incremental.afterStateVector)));
  });
});
